### ISSUE TITLE
Unmatched F-String Fix

### ISSUE THREAD

**Issue by Tohka-aryani** [ibnaleem/instatracker#1]
> Line 64
>     self.write_to_file(f"------{self.date}------\n{self.username} has {initial["followers"]}\n{self.username} is following {initial["following"]} people\n{self.username} has {initial["posts"]} posts\n{self.username} has the following bio: {initial["bio"]}")
>                                                                                 ^^^^^^^^^
> SyntaxError: f-string: unmatched '['

When I first ran the code, it did not work due to double quotes inside the f-string at line 64. However, after changing the inner double quotes with single quotes, I ran the code just fine.

> self.write_to_file(f"------{self.date}------\n{self.username} has {initial['followers']} followers\n{self.username} is following {initial['following']} people\n{self.username} has {initial['posts']} posts\n{self.username} has the following bio: {initial['bio']}")

**Comment by ibnaleem** [comment]
Could you open a PR for this change so I can merge it?
